.MODEL SMALL
.STACK 100H
.DATA 
VAR1 DB ?  
VAR2 DB ?
MSG1 DB 'PLEASE ENTER THE FIRST DIGIT:$' 
MSG2 DB 'PLEASE ENTER THE SECOND DIGIT:$' 
R_MSG DB 'THE RESULT IS:$'
.CODE
MAIN PROC
   ;INITIALIZE DS
   MOV AX,@DATA
   MOV DS,AX
   ;PRINT THE FIRST MESSAGE
   MOV AH,9
   LEA DX,MSG1
   INT 21H
   ;INPUT FIRST VALUE
   MOV AH,1
   INT 21H
   SUB AL,'0'
   MOV BL,AL
   ;GO TO NEW LINE
   MOV AH,2
   MOV DL,0DH
   INT 21H
   MOV DL,0AH
   INT 21H   
   ;PRINT SECOND MESSAGE
   MOV AH,9
   LEA DX,MSG2
   INT 21H
   ;INPUT SECOND VALUE
   MOV AH,1
   INT 21H
   SUB AL,'0'
   MOV BH,AL
   ADD BH,BL
   ADD BH,'0'
   ;GO TO NEW LINE
   MOV AH,2
   MOV DL,0DH
   INT 21H
   MOV DL,0AH
   INT 21H
   ;DISPLAY RESULT MESSAGE
   LEA DX,R_MSG
   MOV AH,9
   INT 21H
   ;DISPLAY CHARACTER
   MOV AH,2 
   MOV DL,BH
   INT 21H
   ;RETURN TO DOS
   MOV AH,4CH
   INT 21H
MAIN ENDP    
    END MAIN
    
    